
package Interfaz;

import caballoajedrez.nodo;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;

/**
 *
 * @author ulseg
 */
public class ChessTable extends javax.swing.JFrame {

    /**
     * Creates new form ChessTable
     */
    public ChessTable() {
        initComponents();
        setLocationRelativeTo(null);
        ///INICIALIZAR ARREGLO DE LABELS
        matrizLabels[0][0] = A1;
        matrizLabels[0][1] = A2;
        matrizLabels[0][2] = A3;
        matrizLabels[0][3] = A4;
        matrizLabels[0][4] = A5;
        matrizLabels[0][5] = A6;
        matrizLabels[0][6] = A7;
        matrizLabels[0][7] = A8;
        
        matrizLabels[1][0] = B1;
        matrizLabels[1][1] = B2;
        matrizLabels[1][2] = B3;
        matrizLabels[1][3] = B4;
        matrizLabels[1][4] = B5;
        matrizLabels[1][5] = B6;
        matrizLabels[1][6] = B7;
        matrizLabels[1][7] = B8;
        
        matrizLabels[2][0] = C1;
        matrizLabels[2][1] = C2;
        matrizLabels[2][2] = C3;
        matrizLabels[2][3] = C4;
        matrizLabels[2][4] = C5;
        matrizLabels[2][5] = C6;
        matrizLabels[2][6] = C7;
        matrizLabels[2][7] = C8;
        
        matrizLabels[3][0] = D1;
        matrizLabels[3][1] = D2;
        matrizLabels[3][2] = D3;
        matrizLabels[3][3] = D4;
        matrizLabels[3][4] = D5;
        matrizLabels[3][5] = D6;
        matrizLabels[3][6] = D7;
        matrizLabels[3][7] = D8;
        
        matrizLabels[4][0] = E1;
        matrizLabels[4][1] = E2;
        matrizLabels[4][2] = E3;
        matrizLabels[4][3] = E4;
        matrizLabels[4][4] = E5;
        matrizLabels[4][5] = E6;
        matrizLabels[4][6] = E7;
        matrizLabels[4][7] = E8;
        
        matrizLabels[5][0] = F1;
        matrizLabels[5][1] = F2;
        matrizLabels[5][2] = F3;
        matrizLabels[5][3] = F4;
        matrizLabels[5][4] = F5;
        matrizLabels[5][5] = F6;
        matrizLabels[5][6] = F7;
        matrizLabels[5][7] = F8;
        
        matrizLabels[6][0] = G1;
        matrizLabels[6][1] = G2;
        matrizLabels[6][2] = G3;
        matrizLabels[6][3] = G4;
        matrizLabels[6][4] = G5;
        matrizLabels[6][5] = G6;
        matrizLabels[6][6] = G7;
        matrizLabels[6][7] = G8;
        
        matrizLabels[7][0] = H1;
        matrizLabels[7][1] = H2;
        matrizLabels[7][2] = H3;
        matrizLabels[7][3] = H4;
        matrizLabels[7][4] = H5;
        matrizLabels[7][5] = H6;
        matrizLabels[7][6] = H7;
        matrizLabels[7][7] = H8;
        
        
        for(int i=0; i<8;i++){
            for(int j=0 ;j<8;j++){
                matrizLabels[i][j].setVisible(false);
            }
        }
    }
    
    javax.swing.JLabel[][] matrizLabels= new javax.swing.JLabel[8][8];
    
    public void trazadoCaballo(ArrayList<nodo> movimientos) throws InterruptedException{
        int x,y;
        for(nodo auxiliar: movimientos){
            x=auxiliar.getX();
            y=auxiliar.getY();
            for(int i=0;i<25000;i++){
                System.out.println("Hola");
            }
            matrizLabels[x-1][y-1].setVisible(true);
            for(int i=0;i<25000;i++){
                System.out.println("Hola");
            }
            matrizLabels[x-1][y-1].setVisible(false
            );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EstructuraTablero = new javax.swing.JPanel();
        A1 = new javax.swing.JLabel();
        A2 = new javax.swing.JLabel();
        A3 = new javax.swing.JLabel();
        A4 = new javax.swing.JLabel();
        A5 = new javax.swing.JLabel();
        A6 = new javax.swing.JLabel();
        A7 = new javax.swing.JLabel();
        A8 = new javax.swing.JLabel();
        B1 = new javax.swing.JLabel();
        B2 = new javax.swing.JLabel();
        B3 = new javax.swing.JLabel();
        B4 = new javax.swing.JLabel();
        B5 = new javax.swing.JLabel();
        B6 = new javax.swing.JLabel();
        B7 = new javax.swing.JLabel();
        B8 = new javax.swing.JLabel();
        C1 = new javax.swing.JLabel();
        C2 = new javax.swing.JLabel();
        C3 = new javax.swing.JLabel();
        C4 = new javax.swing.JLabel();
        C5 = new javax.swing.JLabel();
        C6 = new javax.swing.JLabel();
        C7 = new javax.swing.JLabel();
        C8 = new javax.swing.JLabel();
        D1 = new javax.swing.JLabel();
        D2 = new javax.swing.JLabel();
        D3 = new javax.swing.JLabel();
        D4 = new javax.swing.JLabel();
        D5 = new javax.swing.JLabel();
        D6 = new javax.swing.JLabel();
        D7 = new javax.swing.JLabel();
        D8 = new javax.swing.JLabel();
        E1 = new javax.swing.JLabel();
        E2 = new javax.swing.JLabel();
        E3 = new javax.swing.JLabel();
        E4 = new javax.swing.JLabel();
        E5 = new javax.swing.JLabel();
        E6 = new javax.swing.JLabel();
        E7 = new javax.swing.JLabel();
        E8 = new javax.swing.JLabel();
        F1 = new javax.swing.JLabel();
        F2 = new javax.swing.JLabel();
        F3 = new javax.swing.JLabel();
        F4 = new javax.swing.JLabel();
        F5 = new javax.swing.JLabel();
        F6 = new javax.swing.JLabel();
        F7 = new javax.swing.JLabel();
        F8 = new javax.swing.JLabel();
        G1 = new javax.swing.JLabel();
        G2 = new javax.swing.JLabel();
        G3 = new javax.swing.JLabel();
        G4 = new javax.swing.JLabel();
        G5 = new javax.swing.JLabel();
        G6 = new javax.swing.JLabel();
        G7 = new javax.swing.JLabel();
        G8 = new javax.swing.JLabel();
        H1 = new javax.swing.JLabel();
        H2 = new javax.swing.JLabel();
        H3 = new javax.swing.JLabel();
        H4 = new javax.swing.JLabel();
        H5 = new javax.swing.JLabel();
        H6 = new javax.swing.JLabel();
        H7 = new javax.swing.JLabel();
        H8 = new javax.swing.JLabel();
        Numerología = new javax.swing.JLabel();
        Numerología1 = new javax.swing.JLabel();
        Tablero = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tablero Ajedrez");
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        EstructuraTablero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        A1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        A1.setText("jLabel2");
        EstructuraTablero.add(A1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 60, 60));

        A2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        A2.setText("jLabel2");
        EstructuraTablero.add(A2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 60, 60));

        A3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        A3.setText("jLabel2");
        EstructuraTablero.add(A3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, 60, 60));

        A4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        A4.setText("jLabel2");
        EstructuraTablero.add(A4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 60, 60));

        A5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        A5.setText("jLabel2");
        EstructuraTablero.add(A5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, 60, 60));

        A6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        A6.setText("jLabel2");
        EstructuraTablero.add(A6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, 60, 60));

        A7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        A7.setText("jLabel2");
        EstructuraTablero.add(A7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, 60, 60));

        A8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        A8.setText("jLabel2");
        EstructuraTablero.add(A8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, 60, 60));

        B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        B1.setText("jLabel2");
        EstructuraTablero.add(B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 60, 60));

        B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        B2.setText("jLabel2");
        EstructuraTablero.add(B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 60, 60));

        B3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        B3.setText("jLabel2");
        EstructuraTablero.add(B3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 60, 60));

        B4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        B4.setText("jLabel2");
        EstructuraTablero.add(B4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 60, 60));

        B5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        B5.setText("jLabel2");
        EstructuraTablero.add(B5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 60, 60));

        B6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        B6.setText("jLabel2");
        EstructuraTablero.add(B6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 60, 60));

        B7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        B7.setText("jLabel2");
        EstructuraTablero.add(B7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 60, 60));

        B8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        B8.setText("jLabel2");
        EstructuraTablero.add(B8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, 60, 60));

        C1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        C1.setText("jLabel2");
        EstructuraTablero.add(C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 60, 60));

        C2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        C2.setText("jLabel2");
        EstructuraTablero.add(C2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 60, 60));

        C3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        C3.setText("jLabel2");
        EstructuraTablero.add(C3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 60, 60));

        C4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        C4.setText("jLabel2");
        EstructuraTablero.add(C4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 60, 60));

        C5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        C5.setText("jLabel2");
        EstructuraTablero.add(C5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 60, 60));

        C6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        C6.setText("jLabel2");
        EstructuraTablero.add(C6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 60, 60));

        C7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        C7.setText("jLabel2");
        EstructuraTablero.add(C7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 60, 60));

        C8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        C8.setText("jLabel2");
        EstructuraTablero.add(C8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 60, 60));

        D1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        D1.setText("jLabel2");
        EstructuraTablero.add(D1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 60, 60));

        D2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        D2.setText("jLabel2");
        EstructuraTablero.add(D2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 60, 60));

        D3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        D3.setText("jLabel2");
        EstructuraTablero.add(D3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 60, 60));

        D4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        D4.setText("jLabel2");
        EstructuraTablero.add(D4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 60, 60));

        D5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        D5.setText("jLabel2");
        EstructuraTablero.add(D5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 60, 60));

        D6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        D6.setText("jLabel2");
        EstructuraTablero.add(D6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 60, 60));

        D7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        D7.setText("jLabel2");
        EstructuraTablero.add(D7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 60, 60));

        D8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        D8.setText("jLabel2");
        EstructuraTablero.add(D8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 60, 60));

        E1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        E1.setText("jLabel2");
        EstructuraTablero.add(E1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 60, 60));

        E2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        E2.setText("jLabel2");
        EstructuraTablero.add(E2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 60, 60));

        E3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        E3.setText("jLabel2");
        EstructuraTablero.add(E3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 60, 60));

        E4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        E4.setText("jLabel2");
        EstructuraTablero.add(E4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 60, 60));

        E5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        E5.setText("jLabel2");
        EstructuraTablero.add(E5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 60, 60));

        E6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        E6.setText("jLabel2");
        EstructuraTablero.add(E6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 60, 60));

        E7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        E7.setText("jLabel2");
        EstructuraTablero.add(E7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 60, 60));

        E8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        E8.setText("jLabel2");
        EstructuraTablero.add(E8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 60, 60));

        F1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        F1.setText("jLabel2");
        EstructuraTablero.add(F1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 60, 60));

        F2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        F2.setText("jLabel2");
        EstructuraTablero.add(F2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 60, 60));

        F3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        F3.setText("jLabel2");
        EstructuraTablero.add(F3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 60, 60));

        F4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        F4.setText("jLabel2");
        EstructuraTablero.add(F4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 60, 60));

        F5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        F5.setText("jLabel2");
        EstructuraTablero.add(F5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 60, 60));

        F6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        F6.setText("jLabel2");
        EstructuraTablero.add(F6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 60, 60));

        F7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        F7.setText("jLabel2");
        EstructuraTablero.add(F7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 60, 60));

        F8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        F8.setText("jLabel2");
        EstructuraTablero.add(F8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 60, 60));

        G1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        G1.setText("jLabel2");
        EstructuraTablero.add(G1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 60, 60));

        G2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        G2.setText("jLabel2");
        EstructuraTablero.add(G2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 60, 60));

        G3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        G3.setText("jLabel2");
        EstructuraTablero.add(G3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 60, 60));

        G4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        G4.setText("jLabel2");
        EstructuraTablero.add(G4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 60, 60));

        G5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        G5.setText("jLabel2");
        EstructuraTablero.add(G5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 60, 60));

        G6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        G6.setText("jLabel2");
        EstructuraTablero.add(G6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 60, 60));

        G7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        G7.setText("jLabel2");
        EstructuraTablero.add(G7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 60, 60));

        G8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        G8.setText("jLabel2");
        EstructuraTablero.add(G8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 60, 60));

        H1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        H1.setText("jLabel2");
        EstructuraTablero.add(H1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 60, 60));

        H2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        H2.setText("jLabel2");
        EstructuraTablero.add(H2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 60, 60));

        H3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        H3.setText("jLabel2");
        EstructuraTablero.add(H3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 60, 60));

        H4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        H4.setText("jLabel2");
        EstructuraTablero.add(H4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 60, 60));

        H5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        H5.setText("jLabel2");
        EstructuraTablero.add(H5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 60, 60));

        H6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        H6.setText("jLabel2");
        EstructuraTablero.add(H6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 60, 60));

        H7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        H7.setText("jLabel2");
        EstructuraTablero.add(H7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 60, 60));

        H8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo.png"))); // NOI18N
        H8.setText("jLabel2");
        EstructuraTablero.add(H8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 60, 60));

        Numerología.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        Numerología.setForeground(new java.awt.Color(255, 255, 255));
        Numerología.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Numerología.setText("    1       2       3       4       5       6       7       8");
        Numerología.setToolTipText("");
        EstructuraTablero.add(Numerología, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 480, 50));
        Numerología.getAccessibleContext().setAccessibleName("A  B");

        Numerología1.setFont(new java.awt.Font("Segoe UI Black", 1, 22)); // NOI18N
        Numerología1.setForeground(new java.awt.Color(255, 255, 255));
        Numerología1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Numerología1.setText("<html>H <p><p>  G <p><p> F <p><p> E <p><p> D <p><p> C <p><p> B <p><p> A<html>");
        Numerología1.setToolTipText("");
        EstructuraTablero.add(Numerología1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 40, 490));
        Numerología1.getAccessibleContext().setAccessibleName("");

        Tablero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tablero.png"))); // NOI18N
        Tablero.setText("jLabel1");
        EstructuraTablero.add(Tablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EstructuraTablero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EstructuraTablero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
        
        
        
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChessTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChessTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChessTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChessTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChessTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A1;
    private javax.swing.JLabel A2;
    private javax.swing.JLabel A3;
    private javax.swing.JLabel A4;
    private javax.swing.JLabel A5;
    private javax.swing.JLabel A6;
    private javax.swing.JLabel A7;
    private javax.swing.JLabel A8;
    private javax.swing.JLabel B1;
    private javax.swing.JLabel B2;
    private javax.swing.JLabel B3;
    private javax.swing.JLabel B4;
    private javax.swing.JLabel B5;
    private javax.swing.JLabel B6;
    private javax.swing.JLabel B7;
    private javax.swing.JLabel B8;
    private javax.swing.JLabel C1;
    private javax.swing.JLabel C2;
    private javax.swing.JLabel C3;
    private javax.swing.JLabel C4;
    private javax.swing.JLabel C5;
    private javax.swing.JLabel C6;
    private javax.swing.JLabel C7;
    private javax.swing.JLabel C8;
    private javax.swing.JLabel D1;
    private javax.swing.JLabel D2;
    private javax.swing.JLabel D3;
    private javax.swing.JLabel D4;
    private javax.swing.JLabel D5;
    private javax.swing.JLabel D6;
    private javax.swing.JLabel D7;
    private javax.swing.JLabel D8;
    private javax.swing.JLabel E1;
    private javax.swing.JLabel E2;
    private javax.swing.JLabel E3;
    private javax.swing.JLabel E4;
    private javax.swing.JLabel E5;
    private javax.swing.JLabel E6;
    private javax.swing.JLabel E7;
    private javax.swing.JLabel E8;
    private javax.swing.JPanel EstructuraTablero;
    private javax.swing.JLabel F1;
    private javax.swing.JLabel F2;
    private javax.swing.JLabel F3;
    private javax.swing.JLabel F4;
    private javax.swing.JLabel F5;
    private javax.swing.JLabel F6;
    private javax.swing.JLabel F7;
    private javax.swing.JLabel F8;
    private javax.swing.JLabel G1;
    private javax.swing.JLabel G2;
    private javax.swing.JLabel G3;
    private javax.swing.JLabel G4;
    private javax.swing.JLabel G5;
    private javax.swing.JLabel G6;
    private javax.swing.JLabel G7;
    private javax.swing.JLabel G8;
    private javax.swing.JLabel H1;
    private javax.swing.JLabel H2;
    private javax.swing.JLabel H3;
    private javax.swing.JLabel H4;
    private javax.swing.JLabel H5;
    private javax.swing.JLabel H6;
    private javax.swing.JLabel H7;
    private javax.swing.JLabel H8;
    private javax.swing.JLabel Numerología;
    private javax.swing.JLabel Numerología1;
    private javax.swing.JLabel Tablero;
    // End of variables declaration//GEN-END:variables
}
